/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#79db8d",
        "secondary": "#5d5f5f",
        "error-red": "#ba1a1a",
        "on-secondary-container": "#636565",
        "surface-container-highest": "#dce3f2",
        "background": "#f9f9ff",
        "surface-tint": "#006d30",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#00652c",
        "surface-container": "#e7eefe",
        "on-secondary-fixed": "#1a1c1c",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#becabc",
        "on-tertiary-container": "#d3ffd5",
        "on-primary": "#ffffff",
        "on-primary-container": "#d3ffd5",
        "secondary-fixed-dim": "#c6c7c6",
        "on-tertiary-fixed-variant": "#005323",
        "on-tertiary-fixed": "#00210a",
        "secondary-container": "#e2e3e2",
        "surface-variant": "#dce3f2",
        "secondary-fixed": "#e2e3e2",
        "outline": "#6f7a6e",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface": "#f9f9ff",
        "primary": "#00652c",
        "surface-bright": "#f9f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#454747",
        "on-surface-variant": "#3f493f",
        "primary-fixed-dim": "#79db8d",
        "surface-dim": "#d3daea",
        "on-error": "#ffffff",
        "inverse-primary": "#79db8d",
        "error-container": "#ffdad6",
        "on-surface": "#151c27",
        "tertiary-fixed": "#95f8a7",
        "inverse-surface": "#2a313c",
        "tertiary-container": "#15803d",
        "surface-container-high": "#e2e8f8",
        "success-green": "#00652c",
        "on-primary-fixed": "#00210a",
        "on-primary-fixed-variant": "#005323",
        "on-error-container": "#93000a",
        "on-background": "#151c27",
        "primary-fixed": "#95f8a7",
        "primary-container": "#15803d"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
